Minor refactor of set command in bash script

diff --git a/tutorial/hellocounter/run b/tutorial/hellocounter/run
--- a/tutorial/hellocounter/run
+++ b/tutorial/hellocounter/run
@@ -1,11 +1,11 @@
 #!/bin/sh
-set -x #echo on
+# (e) exist as soon as any line fails, and (x) echo commands as they are run
+set -ex
 echo "$1"
 
 #function mytest {
 #  "$@"
 #  local status = $?
-set -e
 if [[ -n $1 &&  "$1" -eq '-memcheck' ]]; then
   for file in build/*; do valgrind --error-exitcode=1 $file; done
 else
